language: node_js
node_js:
  - "0.6"
  #- "0.8"
  #- "0.10"

env:
  #- CASSANDRA_VERSION=1.0.12
  #- CASSANDRA_VERSION=1.1.12
  - CASSANDRA_VERSION=1.2.5

before_install:
  - sudo rm -rf /etc/security/limits.d/cassandra.conf
  - sudo rm -rf /etc/init.d/cassandra
  - sudo rm -rf /etc/cassandra/
  - sudo rm -rf /var/log/cassandra
  - sudo rm -rf /var/lib/cassandra

install:
  - sudo apt-get install libjna-java
  - sudo apt-get install python-support
  - sudo easy_install pyYaml
  - sudo easy_install pip
  - sudo pip install ccm
  - ccm create test -v $CASSANDRA_VERSION
  - ccm populate -n 3
  - ccm start
  - npm install

script:
  - make test

after_script:
  - ccm remove

notifications:
  email: false
  campfire:
    secure: "24WluBFSwNgmXL+ulZrwEQojuHdCbTQZ5mdLTo5gOsm6j8h6AIjU/U+ubHcu\nNaEufjkCuGwr4LWTInFEjwe+kq6SqiXCstJ8BHu/eM1IYwKbHO9U23WEemVF\n6vWHoNVHWdQeUTLBZRaqYMp07c32q5Xsn5LREXeO6I8f42l0yac="

