language: node_js
node_js:
  - 0.6
  - 0.8

env:
  - CASSANDRA_VERSION=1.0.11
  - CASSANDRA_VERSION=1.1.5

before_install:
  - sudo apt-get install libjna-java
  - sudo apt-get install python-support
  - sudo rm -rf /etc/security/limits.d/cassandra.conf
  - sudo rm -rf /var/log/cassandra
  - sudo rm -rf /var/lib/cassandra

install:
  - curl -LO http://www.apache.org/dist/cassandra/debian/pool/main/c/cassandra/cassandra_${CASSANDRA_VERSION}_all.deb
  - sudo dpkg -i --force-overwrite cassandra_${CASSANDRA_VERSION}_all.deb
  - npm install
  - until nc -z localhost 9160; do sleep 1; done

script:
  - make test

after_script:
  - sudo service cassandra stop

notifications:
  email: false
  campfire: false
