language: node_js
node_js:
  - 0.6
  - 0.7

env:
  - CASSANDRA_VERSION=1.0.9
  - CASSANDRA_VERSION=1.1.0~rc1

before_install:
  - sudo apt-get remove -y --purge cassandra
  - sudo rm -rf /var/log/cassandra
  - sudo rm -rf /var/lib/cassandra

install:
  - curl -LO http://www.apache.org/dist/cassandra/debian/pool/main/c/cassandra/cassandra_$CASSANDRA_VERSION_all.deb
  - sudo dpkg -i cassandra_$CASSANDRA_VERSION_all.deb

after_install:
  - until nc -z localhost 9160; do sleep 1; done

script:
  - make test

after_script:
  - sudo service cassandra stop

matrix:
  allow_failures:
    - env: CASSANDRA_VERSION=1.1.0~rc1
    - node_js: 0.7

notifications:
  email: false
  campfire: false
